language: c
dist: xenial
os:
  - linux
  - osx
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-\S*)?$/
notifications:
  email:
    on_success: change
    on_failure: always

script: 
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then shellcheck bin/*; fi
  - asdf plugin test bridgr $TRAVIS_BUILD_DIR 'bridgr --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
  # Hide "You are in 'detached HEAD' state" message
  - git config --global advice.detachedHead false
